from pathlib import Path
from typing import Any
from dataclasses import dataclass


def PrintRes(res: list[list[bool]], n: int) -> None: ...
def init() -> None: ...
def finalize() -> None: ...
def active() -> bool: ...
def rank() -> int: ...
def nprocs() -> int: ...
def load_circuit(sim: Any, circuit: Any, optimize_level: int | None = None) -> None: ...
def load_circuit_transpiled(sim: Any, circuit: Any) -> None: ...
def load_qasm(path: str | Path) -> Any: ...
def make_zxh_backend(*, disable_x: bool = False, eager_expand_all: bool = False) -> Any: ...
def optimize_circuit(circuit: Any, optimize_level: int = 2, *, allowed_gates: tuple[str, ...] | None = None) -> Any: ...
def analyze_circuit(circuit: Any, *, optimize_level: int | None = None) -> StructureStats: ...
def analyze_qasm(path: str | Path, *, optimize_level: int | None = None) -> StructureStats: ...


@dataclass
class StructureStats:
    compiled_gate_count: int
    compiled_x_type_count: int
    compiled_z_type_count: int
    compiled_h_type_count: int
    compiled_gate_type_counts: dict[str, int]
    M: int
    rho_X: float | None
    rho_M: float | None
    rho_L: float | None
    zh_gate_count: int
    zh_traversal_volume: int
    zh_full_width_volume: int
    clear_gates_calls: int
    expansion_event_count: int
    expansion_events: list[dict[str, Any]]
    final_affine_rows: list[str]
    final_affine_offset: str


class ZXH:
    def __init__(self, n: int, disable_x: bool = False, eager_expand_all: bool = False) -> None: ...
    def set_seed(self, seed: int) -> None: ...
    def clear_seed(self) -> None: ...
    def clear_gates(self) -> None: ...
    def Rz(self, q: int, theta: float) -> None: ...
    def CRz(self, cq: int, q: int, theta: float) -> None: ...
    def CP(self, cq: int, q: int, theta: float) -> None: ...
    def Z(self, q: int) -> None: ...
    def X(self, q: int) -> None: ...
    def CX(self, cq: int, q: int) -> None: ...
    def H(self, q: int) -> None: ...
    def U3(self, q: int, theta: float, lam: float, phi: float) -> None: ...
    def Rx(self, q: int, theta: float) -> None: ...
    def execute(self) -> None: ...
    def measure(self, shots: int) -> list[list[bool]]: ...
    def Sampling(self, shots: int) -> list[list[bool]]: ...
    def required_M(self) -> int: ...
    def num_qubits(self) -> int: ...
