#!/usr/bin/env python3
"""Scan QASM benchmarks, count unsupported gates, and generate sorted circuit list by M."""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from typing import Iterable

import zxhsim

from zxhsim.qasm import load_circuit

# Gates currently accepted by ZXH frontend transpilation path.
SUPPORTED_GATES = {
    "x",
    "swap",
    "cx",
    "ccx",
    "ccz",
    "h",
    "z",
    "cz",
    "rz",
    "crz",
    "rx",
    "ry",
    "p",
    "u1",
    "u2",
    "u3",
    "u",
    "s",
    "sdg",
    "t",
    "tdg",
    "rzz",
    "cp",
    "id",
    "reset",
}

# Operations intentionally ignored in frontend flow.
IGNORED_OPS = {"barrier", "measure"}

QASM_SUFFIXES = {".qasm", ".qasm3"}


def _import_qiskit():
    try:
        from qiskit import QuantumCircuit, transpile
    except Exception as exc:  # pragma: no cover
        raise RuntimeError("qiskit is required. Install it with `pip install qiskit`.") from exc

    qasm3_mod = None
    try:
        from qiskit import qasm3 as qasm3_mod  # type: ignore[assignment]
    except Exception:
        qasm3_mod = None

    return QuantumCircuit, transpile, qasm3_mod


def _normalize_groups(groups_raw: str, root: Path) -> list[str]:
    groups: list[str] = []
    seen = set()
    for part in groups_raw.split(","):
        g = part.strip().lower()
        if not g:
            continue
        if g == "high":
            g = "high" if (root / "high").is_dir() else "large"
        if g in seen:
            continue
        seen.add(g)
        groups.append(g)
    return groups


def _collect_qasm_files(root: Path, groups: Iterable[str]) -> list[Path]:
    out: list[Path] = []
    for group in groups:
        group_dir = root / group
        if not group_dir.is_dir():
            print(f"[WARN] skip missing group directory: {group_dir}")
            continue
        files = sorted(
            p for p in group_dir.rglob("*") if p.is_file() and p.suffix.lower() in QASM_SUFFIXES
        )
        out.extend(files)
    return out


def _load_qasm(path: Path, QuantumCircuit, qasm3_mod):
    errors: list[str] = []

    if path.suffix.lower() == ".qasm3" and qasm3_mod is not None:
        try:
            return qasm3_mod.load(str(path))
        except Exception as exc:
            errors.append(f"qasm3.load failed: {exc}")

    try:
        return QuantumCircuit.from_qasm_file(str(path))
    except Exception as exc:
        errors.append(f"from_qasm_file failed: {exc}")

    if qasm3_mod is not None:
        try:
            return qasm3_mod.load(str(path))
        except Exception as exc:
            errors.append(f"qasm3.load fallback failed: {exc}")

    raise RuntimeError(" | ".join(errors))


def _dump_list(
    out_file: Path,
    supported_with_m: list[tuple[Path, int]],
    unsupported: list[tuple[Path, list[str]]],
) -> None:
    def to_rel_str(p: Path) -> str:
        return str(p).replace("\\", "/")

    supported_sorted = sorted(supported_with_m, key=lambda item: (item[1], to_rel_str(item[0])))

    # Keep M=0 circuits in small section to avoid losing runnable cases.
    small = [(p, m) for p, m in supported_sorted if 0 <= m <= 16]
    medium = [(p, m) for p, m in supported_sorted if 17 <= m <= 24]
    large = [(p, m) for p, m in supported_sorted if 25 <= m <= 32]
    xlarge = [(p, m) for p, m in supported_sorted if m > 32]
    unsupported_sorted = sorted(unsupported, key=lambda item: to_rel_str(item[0]))

    with out_file.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by check_unsupported_gates.py\n")
        f.write("# Path is relative to examples/python/qasm_circuits\n")
        f.write("# Uncomment entries to enable in driver_qasm list mode\n\n")

        f.write(f"# [M-small] 1<=M<=16 (M=0 is also placed here), count={len(small)}\n")
        for p, m in small:
            f.write(f"# M={m}\n")
            f.write(f"{to_rel_str(p)}\n")
        f.write("\n")

        f.write(f"# [M-medium] 17<=M<=24, count={len(medium)}\n")
        for p, m in medium:
            f.write(f"# M={m}\n")
            f.write(f"{to_rel_str(p)}\n")
        f.write("\n")

        f.write(f"# [M-large] 25<=M<=32, count={len(large)} (commented out)\n")
        for p, m in large:
            f.write(f"# M={m}\n")
            f.write(f"# {to_rel_str(p)}\n")
        f.write("\n")

        f.write(f"# [M-extra-large] M>32, count={len(xlarge)} (commented out)\n")
        for p, m in xlarge:
            f.write(f"# M={m}\n")
            f.write(f"# {to_rel_str(p)}\n")
        f.write("\n")

        f.write(f"# [unsupported] count={len(unsupported_sorted)} (commented out)\n")
        for p, reasons in unsupported_sorted:
            reason_str = ",".join(reasons) if reasons else "unknown"
            f.write(f"# unsupported={reason_str}\n")
            f.write(f"# {to_rel_str(p)}\n")


def main() -> None:
    zxhsim.init()
    script_dir = Path(__file__).resolve().parent
    default_root = script_dir / "qasm_circuits"
    default_out = default_root / "circuit_lists.txt"

    parser = argparse.ArgumentParser(
        description="Check benchmark circuits and count unsupported gates in ZXH frontend mapping"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=default_root,
        help="QASM benchmark root directory (default: examples/python/qasm_circuits)",
    )
    parser.add_argument(
        "--groups",
        type=str,
        default="small,medium,large",
        help="Comma-separated groups to scan (default: small,medium,large; supports alias high)",
    )
    parser.add_argument(
        "--opt-level",
        type=int,
        choices=[0, 1, 2, 3],
        default=1,
        help="Qiskit transpile optimization level (default: 1)",
    )
    parser.add_argument(
        "--show-top",
        type=int,
        default=50,
        help="Maximum number of unsupported gates to print (default: 50)",
    )
    parser.add_argument(
        "--list-out",
        type=Path,
        default=default_out,
        help="Output list file (default: examples/python/qasm_circuits/circuit_lists.txt)",
    )
    parser.add_argument(
        "--no-write-list",
        action="store_true",
        help="Do not overwrite circuit list file",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print one-line status for each circuit",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"QASM root not found: {root}")

    groups = _normalize_groups(args.groups, root)
    if not groups:
        raise ValueError("No valid groups provided")

    qasm_files = _collect_qasm_files(root, groups)
    if not qasm_files:
        raise RuntimeError("No QASM files found under selected groups")

    QuantumCircuit, transpile_fn, qasm3_mod = _import_qiskit()

    unsupported_counts: Counter[str] = Counter()
    unsupported_circuit_counts: Counter[str] = Counter()
    supported_with_m: list[tuple[Path, int]] = []
    unsupported_circuits: list[tuple[Path, list[str]]] = []

    parse_fail = 0
    transpile_fail = 0
    compile_fail = 0
    parsed_ok = 0
    transpiled_ok = 0

    for idx, qasm_file in enumerate(qasm_files, start=1):
        rel = qasm_file.relative_to(root)

        try:
            circuit = _load_qasm(qasm_file, QuantumCircuit, qasm3_mod)
            parsed_ok += 1
        except Exception as exc:
            parse_fail += 1
            unsupported_circuits.append((rel, ["parse_error"]))
            print(f"[{idx}/{len(qasm_files)}] [PARSE_FAIL] {rel}: {exc}")
            continue

        try:
            inspect_circuit = transpile_fn(
                circuit,
                basis_gates=sorted(SUPPORTED_GATES),
                optimization_level=args.opt_level,
            )
            transpiled_ok += 1
        except Exception as exc:
            transpile_fail += 1
            unsupported_circuits.append((rel, ["transpile_error"]))
            print(f"[{idx}/{len(qasm_files)}] [TRANSPILE_FAIL] {rel}: {exc}")
            continue

        per_circuit_unsupported: list[str] = []
        for inst in inspect_circuit.data:
            name = inst.operation.name.lower()
            if name in SUPPORTED_GATES or name in IGNORED_OPS:
                continue
            unsupported_counts[name] += 1
            per_circuit_unsupported.append(name)

        if per_circuit_unsupported:
            uniq = sorted(set(per_circuit_unsupported))
            for gate in uniq:
                unsupported_circuit_counts[gate] += 1
            unsupported_circuits.append((rel, uniq))
            if args.verbose:
                print(f"[{idx}/{len(qasm_files)}] [UNSUPPORTED] {rel}: {','.join(uniq)}")
            continue

        # compile-only M estimation via ZXH.required_M (uses ZXH::calc_mem), no execute.
        try:
            sim = zxhsim.ZXH(circuit.num_qubits)
            load_circuit(sim, inspect_circuit, optimize_level=0)
            m = int(sim.required_M())
            supported_with_m.append((rel, m))
            if args.verbose:
                print(f"[{idx}/{len(qasm_files)}] [OK] {rel} M={m}")
        except Exception as exc:
            compile_fail += 1
            unsupported_circuits.append((rel, ["compile_error"]))
            print(f"[{idx}/{len(qasm_files)}] [COMPILE_FAIL] {rel}: {exc}")

    print("\n=== Scan Summary ===")
    print(f"root: {root}")
    print(f"groups: {','.join(groups)}")
    print(f"total_qasm_files: {len(qasm_files)}")
    print(f"parsed_ok: {parsed_ok}")
    print(f"parse_fail: {parse_fail}")
    print(f"transpiled_ok: {transpiled_ok}")
    print(f"transpile_fail: {transpile_fail}")
    print(f"compile_fail: {compile_fail}")
    print(f"supported_circuits: {len(supported_with_m)}")
    print(f"unsupported_circuits: {len(unsupported_circuits)}")

    print("\n=== Unsupported Gates (by occurrence) ===")
    if not unsupported_counts:
        print("none")
    else:
        for gate, count in unsupported_counts.most_common(args.show_top):
            circuit_cnt = unsupported_circuit_counts[gate]
            print(f"{gate:20s} occurrences={count:<8d} circuits={circuit_cnt}")

    if supported_with_m:
        only_m = [m for _, m in supported_with_m]
        print("\n=== Required M (compile-only) ===")
        print(f"M_min: {min(only_m)}")
        print(f"M_max: {max(only_m)}")
        print(f"M_avg: {sum(only_m) / len(only_m):.2f}")

    if not args.no_write_list:
        out_file = args.list_out.resolve()
        _dump_list(out_file, supported_with_m, unsupported_circuits)
        print(f"\nList written to: {out_file}")


if __name__ == "__main__":
    try:
        main()
    finally:
        zxhsim.finalize()
